export { default as hostname } from './hostname';
export { default as whoami } from './whoami';
export { default as sudo } from './sudo';
export { default as pwd } from './pwd';
export { default as help } from './help';
export { default as clear } from './clear';
export { default as ls } from './ls';
export { default as cat } from './cat';
export { default as cd } from './cd';